### ISSUE TITLE
Problems with HTML-Table

### ISSUE THREAD

**Issue by seem2810** [protonemedia/laravel-xss-protection#4]
Hi there,

we use the laravel-xss-protection and got problems with 2 types of contents:
1) we use an wysiwyg editor and if the editor contains a table, the request will be changed to null
2) same with a file content from draw.io

What can we change?

**Comment by voku** [comment]
Hi, I am the developer of the underlying anti-xss library, if you share your html that will trigger the false-positives, we can properly fix it. 😊
